packages:
  - 'plugins/*'
  - 'packages/*'

catalogs:
  deps:
    # typescript-eslint ecosystem (keep versions aligned)
    '@typescript-eslint/utils': '^8.57.0'

  dev:
    # typescript-eslint ecosystem (keep versions aligned)
    '@typescript-eslint/rule-tester': '8.59.3'
    typescript-eslint: '8.59.3'

    # build & test toolchain
    tsdown: '0.22.0'
    vitest: '4.1.6'

    # plugin dev utilities
    '@marcalexiei/prettier-config': '2.0.0'
    dedent: '1.7.2'
    eslint-doc-generator: '3.3.2'
    prettier: '3.8.3'

allowBuilds:
  unrs-resolver: true

minimumReleaseAge: 1440
trustPolicy: no-downgrade

dedupePeers: true
dedupePeerDependents: true
