name: CI

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test on Node ${{ matrix.node }} with ESLint ${{ matrix.eslint }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node:
          - 20
          - 22
          - 24
          - 25
        eslint:
          - 9
          - 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@6735bb9dd019900ebc16ce34e13c118b3917d1f7 # v1.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install ESLint (if needed)
        if: ${{ matrix.eslint != 10 }}
        run: pnpm -r --include-workspace-root install eslint@${{ matrix.eslint }} --save-dev

      - name: Run test
        run: pnpm run test

  code-checks:
    name: Code checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@6735bb9dd019900ebc16ce34e13c118b3917d1f7 # v1.2.0

      - name: Build
        run: pnpm run build

      - name: Typecheck
        run: pnpm run typecheck

      - name: Format check
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint

  ci-ok:
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
      - code-checks
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
